name: Documentation improvement
description: Suggest a documentation change.
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: textarea
    id: page
    attributes:
      label: Page or section
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: Suggested improvement
    validations:
      required: true
